name: CI

on:
  push:


permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build HTML
        run: pnpm build:html

      - name: Build PDF
        run: pnpm build:pdf

      - name: Build PPTX
        run: pnpm build:pptx
